language: node_js

node_js:
  - "8.9.4"

sudo: false

before_script:
  - echo 'Europe/Paris' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - export TZ=Europe/Paris
  