name: Test

on: [push, release, pull-request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node: [8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install asterism, alone
      run: npm install
    - name: Check syntax with lint
      run: npm run lint
    - name: Try a dist:compact command
      run: npm run dist:compact
    - name: Try a classical dist command
      run: npm run dist
    - name: Run automated tests
      env:
        # Set Europe/Paris timezone, but without summer time offset: equiv to Algiers
        TZ: /usr/share/zoneinfo/Africa/Johannesburg
      run: npm run test:rerun
